/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade;

import java.util.concurrent.ExecutionException;

/**
 *
 autor: Michael Junges
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Conta conta1;
    Conta conta2;
    
    public TelaPrincipal() {
        initComponents();
        
        conta1 = new Conta();
        conta2 = new Conta();
        
        System.out.println("Saldo Inicial:");
        
        conta1.setConta(1);
        conta1.setNome("Michael");
        conta1.setCidade("Capitão");
        conta1.setTelefone("(51)99599-9999");
        conta1.setValorConta(500.00);
        conta1.setChequeEspecial(1000.00); 

        conta2.setConta(2);
        conta2.setNome("Vinícius");
        conta2.setCidade("Lajeado");
        conta2.setTelefone("(51)99999-9999");
        conta2.setValorConta(1000.00);
        conta2.setChequeEspecial(300.00);
        
        LblNome.setText(conta1.getNome());
        LblConta.setText(String.valueOf(conta1.getConta()));
        LblSaldo.setText(String.valueOf(conta1.getValorConta()));
        LblChequeEspecial.setText(String.valueOf(conta1.getChequeEspecial()));
        LblCidade.setText(conta1.getCidade());
        LblTelefone.setText(conta1.getTelefone());
        
        LblNome1.setText(conta2.getNome());
        LblConta1.setText(String.valueOf(conta2.getConta()));
        LblSaldo1.setText(String.valueOf(conta2.getValorConta()));
        LblChequeEspecial1.setText(String.valueOf(conta2.getChequeEspecial()));
        LblCidade1.setText(conta2.getCidade());
        LblTelefone1.setText(conta2.getTelefone());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnTransferencia = new javax.swing.JButton();
        LblConta = new javax.swing.JLabel();
        LblNome = new javax.swing.JLabel();
        LblSaldo = new javax.swing.JLabel();
        LblChequeEspecial = new javax.swing.JLabel();
        LblCidade = new javax.swing.JLabel();
        LblTelefone = new javax.swing.JLabel();
        LblConta1 = new javax.swing.JLabel();
        LblNome1 = new javax.swing.JLabel();
        LblSaldo1 = new javax.swing.JLabel();
        LblChequeEspecial1 = new javax.swing.JLabel();
        LblCidade1 = new javax.swing.JLabel();
        LblTelefone1 = new javax.swing.JLabel();
        TxtValor = new javax.swing.JTextField();
        TxtValor1 = new javax.swing.JTextField();
        BtnTransferencia1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        BtnTransferencia.setText("Transferir");
        BtnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransferenciaActionPerformed(evt);
            }
        });

        LblConta.setText("Conta");

        LblNome.setText("Nome");

        LblSaldo.setText("Saldo");

        LblChequeEspecial.setText("Cheque Especial");

        LblCidade.setText("Cidade");

        LblTelefone.setText("Telefone");

        LblConta1.setText("Conta");

        LblNome1.setText("Nome");

        LblSaldo1.setText("Saldo");

        LblChequeEspecial1.setText("Cheque Especial");

        LblCidade1.setText("Cidade");

        LblTelefone1.setText("Telefone");

        BtnTransferencia1.setText("Transferir");
        BtnTransferencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransferencia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblConta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblChequeEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnTransferencia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblConta1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblChequeEspecial1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnTransferencia1)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblConta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblChequeEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblConta1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblChequeEspecial1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTransferencia)
                    .addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTransferencia1))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(385, 260));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransferenciaActionPerformed
        try{
            double transf = Double.parseDouble(TxtValor.getText());
            if(conta1.credito(transf)){
                conta2.debito(transf);
            }
            LblSaldo.setText(String.valueOf(conta1.getValorConta()));
            LblSaldo1.setText(String.valueOf(conta2.getValorConta()));
            TxtValor.setText("0");
        }catch(Exception ex){
            System.out.println("Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_BtnTransferenciaActionPerformed

    private void BtnTransferencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransferencia1ActionPerformed
        try{
            double transf = Double.parseDouble(TxtValor1.getText());
            if(conta2.credito(transf)){
                conta1.debito(transf);
            }
            LblSaldo1.setText(String.valueOf(conta2.getValorConta()));
            LblSaldo.setText(String.valueOf(conta1.getValorConta()));
            TxtValor1.setText("0");
        }catch(Exception ex){
            System.out.println("Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_BtnTransferencia1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTransferencia;
    private javax.swing.JButton BtnTransferencia1;
    private javax.swing.JLabel LblChequeEspecial;
    private javax.swing.JLabel LblChequeEspecial1;
    private javax.swing.JLabel LblCidade;
    private javax.swing.JLabel LblCidade1;
    private javax.swing.JLabel LblConta;
    private javax.swing.JLabel LblConta1;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblNome1;
    private javax.swing.JLabel LblSaldo;
    private javax.swing.JLabel LblSaldo1;
    private javax.swing.JLabel LblTelefone;
    private javax.swing.JLabel LblTelefone1;
    private javax.swing.JTextField TxtValor;
    private javax.swing.JTextField TxtValor1;
    // End of variables declaration//GEN-END:variables

}
